# SELECT b.TITLE, b.BOARD_ID, r.REPLY_ID, r.WRITER_ID, b.CONTENTS, 
#        DATE_FORMAT(b.CREATED_DATE, '%Y-%m-%d') AS CREATED_DATE
# FROM USED_GOODS_BOARD b 
# left JOIN USED_GOODS_REPLY r 
# ON b.BOARD_ID = r.BOARD_ID
# WHERE DATE_FORMAT(b.CREATED_DATE, '%Y-%m') = '2022-10'
# ORDER BY b.CREATED_DATE ASC, b.TITLE ASC;

SELECT  A.TITLE
        , A.BOARD_ID
        , B.REPLY_ID
        , B.WRITER_ID
        , B.CONTENTS
        , DATE_FORMAT(B.CREATED_DATE, '%Y-%m-%d') AS CRAETED_DATE
  FROM  USED_GOODS_BOARD AS A
 INNER
  JOIN  USED_GOODS_REPLY AS B
    ON  A.BOARD_ID = B.BOARD_ID
 WHERE  SUBSTR(A.CREATED_DATE,1,7) = '2022-10'
 ORDER
    BY  B.CREATED_DATE ASC, A.TITLE ASC;
